---
# Jupyter LLM docker compose by Matthew Printz

version: '3'
services:
  jupyter:
    build:
      dockerfile: ${DOCKERFILE:-Dockerfile}
      context: .
    ports:
      - "8888:8888"
    environment:
      - DEBUG=1
      - JUPYTER_SERVER=http://jupyter:8888
      - JUPYTER_TOKEN=89f73481102c46c0bc13b2998f9a4fce
      - OPENAI_API_KEY
      - PYTHONPATH=/bunsen
      - ENABLE_CHECKPOINTS=true
      - TOOL_ENABLED_ASK_USER=true
      - TOOL_ENABLED_RUN_CODE=true
    volumes:
      - .:/bunsen
    command: ["beaker", "dev", "watch", "--ip", "0.0.0.0"]
