---
# Automatically build and publish

name: Build and Publish

# yamllint disable-line rule:truthy
on:
  push:
    tags: ['v*']

jobs:
    build:
        name: Build & Publish
        runs-on: ubuntu-latest
        permissions:
            id-token: write
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Install hatch
              shell: bash
              run: |
                  pip install hatch hatchling
            - name: hatch build
              shell: bash
              run: |
                  hatch build

            - name: Publish package distributions to PyPI
              uses: pypa/gh-action-pypi-publish@release/v1

            # - name: hatch publish
            #   shell: bash
            #   run: |
            #       hatch publish
